apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: gatewatch-api-security-console
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "1m"
spec:
  rules:
    - host: gatewatch.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: gatewatch-api-security-console
                port:
                  number: 80
